kind: pipeline
type: docker
name: terraform-version-upgrade

steps:
- name: init
  image: wirelab/docker-terragrunt:v0.11.14
  user: root
  commands:
  - terragrunt init
  when:
    branch:
      exclude: [ master ]
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: validate
  image: wirelab/docker-terragrunt:v0.11.14
  commands:
  - terragrunt validate
  when:
    branch:
      exclude: [ master ]
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_KEY:
      from_secret: TF_VAR_KEY
    TF_VAR_SECRET:
      from_secret: TF_VAR_SECRET

- name: plan
  image: wirelab/docker-terragrunt:v0.11.14
  user: root
  commands:
  - terragrunt plan -lock=false -out=plan
  when:
    event: push
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_KEY:
      from_secret: TF_VAR_KEY
    TF_VAR_SECRET:
      from_secret: TF_VAR_SECRET

- name: apply
  image: wirelab/docker-terragrunt:v0.11.14
  user: root
  commands:
  - terragrunt apply -auto-approve -lock=false plan
  when:
    branch:
      include: [ master ]
      exclude: [ plan/* ]
    event: push
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_KEY:
      from_secret: TF_VAR_KEY
    TF_VAR_SECRET:
      from_secret: TF_VAR_SECRET

- name: checklist
  image: wirelab/docker-terragrunt:v0.11.14
  user: root
  commands:
  - terragrunt 0.12checklist
  when:
    event: push
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_KEY:
      from_secret: TF_VAR_KEY
    TF_VAR_SECRET:
      from_secret: TF_VAR_SECRET
