pipeline {
    agent any

    environment {
      AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
      AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
      TF_VAR_KEY = credentials('TF_VAR_KEY')
      TF_VAR_SECRET = credentials('TF_VAR_SECRET')
    }

    stages {
      stage('Initialize Terragrunt') {
          when {
              not {
                  branch 'master'
              }
          }
          steps {
              script {
                  docker.image('wirelab/docker-terragrunt:v0.11.14').inside("-v /var/run/docker.sock:/var/run/docker.sock \
                                                                             --entrypoint='' \
                                                                             -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                                                                             -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY") { c ->
                      sh '''
            					terragrunt init
                      '''
                  }
              }
          }
      }
      stage('Terragrunt Validate') {
          when {
              not {
                  branch 'master'
              }
          }
          steps {
              script {
                  docker.image('wirelab/docker-terragrunt:v0.11.14').inside("-v /var/run/docker.sock:/var/run/docker.sock \
                                                                             --entrypoint='' \
                                                                             -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                                                                             -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY") { c ->
                      sh '''
                      terragrunt validate
                      '''
                  }
              }
          }
      }
      stage('Terragrunt Plan') {
          steps {
              script {
                  docker.image('wirelab/docker-terragrunt:v0.11.14').inside("-v /var/run/docker.sock:/var/run/docker.sock \
                                                                             --entrypoint='' \
                                                                             -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                                                                             -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                                                                             -e TF_VAR_KEY=$TF_VAR_KEY \
                                                                             -e TF_VAR_SECRET=$TF_VAR_SECRET") { c ->
                      sh '''
                      terragrunt plan -lock=false -out=plan
                      '''
                  }
              }
          }
      }
      stage('Terragrunt Apply NonProd') {
          when {
              expression {
                  return env.GIT_BRANCH == "origin/master"
              }
          }
          steps {
              script {
                  docker.image('wirelab/docker-terragrunt:v0.11.14').inside("-v /var/run/docker.sock:/var/run/docker.sock \
                                                                             --entrypoint='' \
                                                                             -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                                                                             -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                                                                             -e TF_VAR_KEY=$TF_VAR_KEY \
                                                                             -e TF_VAR_SECRET=$TF_VAR_SECRET") { c ->
                      sh '''
                      terragrunt apply -auto-approve -parallelism=50 plan
                      '''
                  }
              }
          }
      }
      stage('Terragrunt Checklist') {
          steps {
              script {
                  docker.image('wirelab/docker-terragrunt:v0.11.14').inside("-v /var/run/docker.sock:/var/run/docker.sock \
                                                                             --entrypoint='' \
                                                                             -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                                                                             -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                                                                             -e TF_VAR_KEY=$TF_VAR_KEY \
                                                                             -e TF_VAR_SECRET=$TF_VAR_SECRET") { c ->
                      sh '''
                      terragrunt 0.12checklist
                      '''
                  }
              }
          }
      }
    }
    post {
        always {
            cleanWs()
        }
    }
}
